### ISSUE TITLE
Homebridge stürzt ab nach [AVR] get Mute => setNewValue: function ()

### ISSUE THREAD

**Issue by beckern** [marcelkordek/homebridge-harman-kardon-avr#5]
Hallo,
ich habe gerade das Plugin installiert und bekomme folgende Fehlermeldung:

8.7.2020, 09:45:14] 8.7.2020, 09:45:14] [AVR] get Mute => setNewValue: function () {
        var args = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            args[_i] = arguments[_i];
        }
        if (called) {
            throw new Error("This callback function has already been called by someone else; it can only be called one time.");
        }
        else {
            called = true;
            return func.apply(void 0, args);
        }
    }
[8.7.2020, 09:45:15] TypeError: callback is not a function
    at Mute.<anonymous> (/usr/local/lib/node_modules/homebridge-harman-kardon-avr/index.js:172:7)
    at Mute.emit (events.js:198:13)
    at Mute.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Mute.Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:488:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1215:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1143:10)
    at HAPServer.emit (events.js:198:13)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:756:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:280:24)
    at IncomingMessage.emit (events.js:198:13)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[8.7.2020, 09:45:15] Got SIGTERM, shutting down Homebridge... {
        var args = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            args[_i] = arguments[_i];
        }
        if (called) {
            throw new Error("This callback function has already been called by someone else; it can only be called one time.");
        }
        else {
            called = true;
            return func.apply(void 0, args);
        }
    }
[8.7.2020, 09:45:15] TypeError: callback is not a function
    at Mute.<anonymous> (/usr/local/lib/node_modules/homebridge-harman-kardon-avr/index.js:172:7)
    at Mute.emit (events.js:198:13)
    at Mute.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Mute.Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:488:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1215:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1143:10)
    at HAPServer.emit (events.js:198:13)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:756:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:280:24)
    at IncomingMessage.emit (events.js:198:13)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[8.7.2020, 09:45:15] Got SIGTERM, shutting down Homebridge...

Angesteuert wird ein HK AVR151.
Homebridge auf dem aktuellen Stand und relativ frisch aufgesetz... läuft ansonsten ohne Probleme.

Würde mich freuen, wenn das Problem behoben werden kann.

Danke
beckern

**Comment by marcelkordek** [comment]
Hallo beckern,

ich kann es gerade leider nicht testen. Der Fehler müsste jetzt aber mit v2.2.3 behoben sein.

Vielen Dank und Gruß
Marcel

**Comment by beckern** [comment]
Hallo, 
vielen Dank. Scheint zu funktionieren. 

Jetzt habe ich allerdings das Phänomen, dass alle Geräte nicht mehr in HomeKit zu sehen sind/nach kurzer Zeit verschwinden. 

Das Problem hatte ich auch schon bei einem anderen Plugin, wurde aber noch nicht gelöst. 

Einzig ein Gerät welches als Accessorie und nicht in Platform in der config.json eingetragen ist wird noch angezeigt!

Gruß beckern

**Comment by marcelkordek** [comment]
Hallo beckern,

ich kann das Problem leider noch nicht nachstellen. Welche Homebridge Version nutzt du?
Es könnte evtl. an der Version 1.1.1 liegen.

Gruß

**Comment by beckern** [comment]
Hallo,

ja, ich nutze 1.1.1

 

Gruß

 

Von: Marcel [mailto:notifications@github.com] 
Gesendet: Donnerstag, 30. Juli 2020 10:04
An: marcelkordek/homebridge-harman-kardon-avr
Cc: beckern; Author
Betreff: Re: [marcelkordek/homebridge-harman-kardon-avr] Homebridge stürzt ab nach [AVR] get Mute => setNewValue: function () (#5)

 

Hallo beckern,

ich kann das Problem leider noch nicht nachstellen. Welche Homebridge Version nutzt du?
Es könnte evtl. an der Version 1.1.1 liegen.

Gruß
